server:
  port: 8085
spring:
  datasource:
    username: "mayur28"
    password: "M@yur2821"
    url: "jdbc:sqlserver://shofferstop.database.windows.net:1433;database=ShofferStop_DB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30"
  jpa:
    hibernate:
      ddl-auto: "validate"
  security:
    user:
      name: "root"
      password: "root"  